"""
Markdown Reporter

Generates Markdown reports for documentation.

Version: 1.0.0 (Session 47 Refactoring)
"""

import logging
from typing import Any, Optional

from .base_reporter import BaseReporter, ReportFormat

logger = logging.getLogger(__name__)


class MarkdownReporter(BaseReporter):
    """
    Generate Markdown reports.
    
    Example:
        >>> reporter = MarkdownReporter()
        >>> md_content = reporter.generate(result)
    """
    
    @property
    def format(self) -> ReportFormat:
        return ReportFormat.MARKDOWN
    
    def generate(self, result: Any, title: Optional[str] = None, **kwargs) -> str:
        """Generate Markdown report."""
        context = self._prepare_context(result, title)
        
        lines = [
            f"# {context['title']}",
            "",
            f"**Generated:** {context['scan_time']}  ",
            f"**Target:** `{context['target']}`  ",
            f"**Execution Time:** {context['execution_time']}s  ",
            f"**Overall Risk:** {context['overall_risk']}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"- **Total Findings:** {context['summary']['total_findings']}",
            f"- **Unique Issues:** {context['summary']['unique_findings']}",
            f"- **Critical:** {context['summary']['critical_count']}",
            f"- **High:** {context['summary']['high_count']}",
            f"- **Medium:** {context['summary']['medium_count']}",
            f"- **Low:** {context['summary']['low_count']}",
            f"- **Duplicates Removed:** {context['summary']['duplicates_removed']}",
            "",
            "---",
            "",
            "## Severity Breakdown",
            "",
            "| Severity | Count | Percentage |",
            "|----------|-------|------------|",
        ]
        
        for sev in context['severity_breakdown']:
            lines.append(f"| {sev['name']} | {sev['count']} | {sev['percentage']}% |")
        
        lines.extend([
            "",
            "---",
            "",
            "## Scanner Breakdown",
            "",
            "| Scanner | Findings | Percentage |",
            "|---------|----------|------------|",
        ])
        
        for scanner in context['scanner_breakdown']:
            lines.append(f"| {scanner['name']} | {scanner['count']} | {scanner['percentage']}% |")
        
        lines.extend([
            "",
            "---",
            "",
            "## Top Priority Findings",
            "",
        ])
        
        for idx, finding in enumerate(context['top_findings'], 1):
            emoji = self._get_severity_emoji(finding['severity'])
            lines.extend([
                f"### {idx}. {emoji} {finding['title']}",
                "",
                f"**Severity:** {finding['severity']}  ",
                f"**File:** `{finding['file_path']}`  ",
                f"**Lines:** {finding['line_start']}-{finding['line_end']}  ",
                f"**Scanner:** {finding['scanner']}  ",
                f"**Priority Score:** {finding['priority_score']}/100",
                "",
                f"**Description:** {finding['description']}",
                "",
            ])
            
            if self.include_code_snippets and finding.get('code_snippet'):
                lines.extend([
                    "**Code:**",
                    "```",
                    finding['code_snippet'],
                    "```",
                    "",
                ])
            
            if finding.get('cwe_ids'):
                lines.append(f"**CWE:** {', '.join(finding['cwe_ids'])}")
                lines.append("")
        
        lines.extend([
            "---",
            "",
            "*Report generated by Security Assistant*",
        ])
        
        return "\n".join(lines)
