"""
Text Reporter Implementation

Generates plain text reports for terminal output and logs.

Version: 1.0.0
"""

import logging
from typing import Any, Dict

from .base_reporter import BaseReporter, ReportFormat

logger = logging.getLogger(__name__)


class TextReporter(BaseReporter):
    """
    Generates plain text reports.
    Suitable for terminal output, logs, and simple file output.
    """

    @property
    def format(self) -> ReportFormat:
        return ReportFormat.TEXT

    def generate(self, result: Any, **kwargs) -> str:
        """
        Generate plain text report.

        Args:
            result: OrchestrationResult
            **kwargs: title, template_name, etc.

        Returns:
            Plain text content
        """
        context = self._prepare_context(result, kwargs.get("title"))
        return self._generate_text(context)

    def _generate_text(self, context: Dict[str, Any]) -> str:
        """Generate plain text from context."""
        lines = [
            "=" * 80,
            context["title"].center(80),
            "=" * 80,
            "",
            f"Generated: {context['generated_at']}",
            f"Target: {context['target']}",
            f"Execution Time: {context['execution_time']}s",
            "",
            "-" * 80,
            "EXECUTIVE SUMMARY",
            "-" * 80,
            f"Total Findings:      {context['summary']['total_findings']}",
            f"Unique Issues:       {context['summary']['unique_findings']}",
            f"Critical:            {context['summary']['critical_count']}",
            f"High:                {context['summary']['high_count']}",
            f"Medium:              {context['summary']['medium_count']}",
            f"Low:                 {context['summary']['low_count']}",
            f"Duplicates Removed:  {context['summary']['duplicates_removed']}",
            "",
            "-" * 80,
            "SEVERITY BREAKDOWN",
            "-" * 80,
        ]

        for sev in context["severity_breakdown"]:
            lines.append(f"  {sev['name']:12} {sev['count']:5}  ({sev['percentage']}%)")

        lines.extend(
            [
                "",
                "-" * 80,
                "TOP PRIORITY FINDINGS",
                "-" * 80,
            ]
        )

        for idx, finding in enumerate(context["top_findings"], 1):
            lines.extend(
                [
                    "",
                    f"{idx}. [{finding['severity']}] {finding['title']}",
                    f"   File: {finding['file_path']}:{finding['line_start']}",
                    f"   Scanner: {finding['scanner']}",
                    f"   Priority: {finding['priority_score']}/100",
                    f"   {finding['description'][:200]}{'...' if len(finding['description']) > 200 else ''}",
                ]
            )

            if self.include_code_snippets and finding.get("code_snippet"):
                lines.extend(
                    [
                        "   Code:",
                        "   " + "-" * 40,
                    ]
                )
                for code_line in finding["code_snippet"].split("\n")[:5]:
                    lines.append(f"   {code_line}")
                lines.append("   " + "-" * 40)

        lines.extend(
            [
                "",
                "=" * 80,
                "Report generated by Security Assistant".center(80),
                "=" * 80,
            ]
        )

        return "\n".join(lines)
