"""
Configure Command

Interactive configuration wizard for Security Assistant.
"""

import os
from pathlib import Path
from typing import Dict, Optional


def get_input(prompt: str, default: Optional[str] = None) -> str:
    """Get user input with optional default."""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "

    value = input(full_prompt).strip()
    return value if value else default or ""


def cmd_configure():
    """Run interactive configuration wizard."""
    print("🛠️  Security Assistant Configuration")
    print("====================================")
    print("This wizard will help you set up your .env file.\n")

    config: Dict[str, str] = {}

    # Load existing .env if present
    if Path(".env").exists():
        print("📝 Found existing .env file. Press Enter to keep current values.\n")
        with open(".env") as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, val = line.strip().split("=", 1)
                    config[key] = val

    # 1. General Settings
    print("--- General Settings ---")
    config["SA_SCAN_TARGET"] = get_input(
        "Default scan target", config.get("SA_SCAN_TARGET", ".")
    )
    config["SA_MAX_WORKERS"] = get_input(
        "Max parallel workers", config.get("SA_MAX_WORKERS", "3")
    )

    # 2. Scanners
    print("\n--- Scanners ---")
    config["SA_BANDIT_ENABLED"] = get_input(
        "Enable Bandit (Python)", config.get("SA_BANDIT_ENABLED", "true")
    )
    config["SA_SEMGREP_ENABLED"] = get_input(
        "Enable Semgrep (General)", config.get("SA_SEMGREP_ENABLED", "true")
    )
    config["SA_TRIVY_ENABLED"] = get_input(
        "Enable Trivy (SCA)", config.get("SA_TRIVY_ENABLED", "true")
    )

    # 3. Intelligence
    print("\n--- Intelligence Features ---")
    config["SA_ENABLE_KEV"] = get_input(
        "Enable KEV Enrichment (CISA)", config.get("SA_ENABLE_KEV", "true")
    )
    config["SA_ENABLE_FP_DETECTION"] = get_input(
        "Enable False Positive Detection", config.get("SA_ENABLE_FP_DETECTION", "true")
    )
    config["SA_ENABLE_REACHABILITY"] = get_input(
        "Enable Reachability Analysis", config.get("SA_ENABLE_REACHABILITY", "true")
    )

    # 4. CI/CD
    print("\n--- CI/CD Integration ---")
    config["SA_FAIL_ON_CRITICAL"] = get_input(
        "Fail build on CRITICAL findings", config.get("SA_FAIL_ON_CRITICAL", "true")
    )
    config["SA_FAIL_ON_HIGH"] = get_input(
        "Fail build on HIGH findings", config.get("SA_FAIL_ON_HIGH", "false")
    )

    # Save to .env
    print("\nWriting to .env...")
    with open(".env", "w") as f:
        f.write("# Security Assistant Configuration\n")
        f.write(f"# Generated by 'security-assistant configure' on {os.times}\n\n")

        for key, value in config.items():
            f.write(f"{key}={value}\n")

    print("✅ Configuration saved successfully!")
    return 0
